// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBgWZR7G3grsaw6B1w_e3jahdcuoOrxYg',
    appId: '1:845253834243:web:650aa6dd675fdcacac4036',
    messagingSenderId: '845253834243',
    projectId: 'antam-f2ee7',
    authDomain: 'antam-f2ee7.firebaseapp.com',
    storageBucket: 'antam-f2ee7.firebasestorage.app',
    measurementId: 'G-XF1B9VJWJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwSRciyIAeeam8BPnXujyuIpeS3Z2a0s',
    appId: '1:845253834243:android:792e3ef21330c4f9ac4036',
    messagingSenderId: '845253834243',
    projectId: 'antam-f2ee7',
    storageBucket: 'antam-f2ee7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtwSRciyIAeeam8BPnXujyuIpeS3Z2a0s',
    appId: '1:845253834243:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '845253834243',
    projectId: 'antam-f2ee7',
    storageBucket: 'antam-f2ee7.firebasestorage.app',
    iosBundleId: 'com.company.antam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtwSRciyIAeeam8BPnXujyuIpeS3Z2a0s',
    appId: '1:845253834243:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '845253834243',
    projectId: 'antam-f2ee7',
    storageBucket: 'antam-f2ee7.firebasestorage.app',
    iosBundleId: 'com.company.antam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBgWZR7G3grsaw6B1w_e3jahdcuoOrxYg',
    appId: '1:845253834243:web:650aa6dd675fdcacac4036',
    messagingSenderId: '845253834243',
    projectId: 'antam-f2ee7',
    authDomain: 'antam-f2ee7.firebaseapp.com',
    storageBucket: 'antam-f2ee7.firebasestorage.app',
    measurementId: 'G-XF1B9VJWJB',
  );
}
